sonar.projectKey=AltaPay_plugin-prestashop_37fe3889-2a05-47ac-b3f9-4c4169e24be3
sonar.coverage.exclusions=**
sonar.cpd.exclusions=**
# Ignore Sonar rule: Property names should match ^[a-z][a-zA-Z0-9]*$
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S116
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php